Feed/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from RoutePages import views as RoutePageViews



app_name= "Feed"

urlpatterns=[
    path('', views.display_feed, name='feed'),
]

Rambler/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from Feed import views as feed_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', feed_views.display_feed, name='home'),
    path('users/', include('users.urls')),
    path('routeplanner/', include('RoutePlanner.urls')),
    path('feed/', include('Feed.urls')),
    path('weather/', include('Weather.urls')),
    path('route/', include('RoutePages.urls')),
    path('chat/', include('chat.urls')),
]

WalkingApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login_page.html', form_class=LoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('disable/', views.disable, name='disable'),
]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

#Authentication form
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)


#User form for signup and profile
class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    #EmailField validates itself
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), required=False)
    password_confirmation = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), required=False)

    def clean_username(self):
        data = self.cleaned_data['username']

        #Only if changing username
        if data != self.get_initial_for_field(self, 'username'):
            #Check not already taken
            if User.objects.filter(username__iexact=data).exists():
                raise forms.ValidationError('Username already taken.')
        
        return data

    def clean(self):
        #Password with no confirmation
        if self.data['password'] and not self.data['password_confirmation']:
            self.add_error('password_confirmation', 'Please confirm your password.')

        #Confirmation with no password
        if not self.data['password'] and self.data['password_confirmation']:
            self.add_error('password', 'Please enter a password.')
        
        #Password and confirmation don't match
        if self.data['password'] and self.data['password_confirmation']:
            if self.data['password'] != self.data['password_confirmation']:
                err = "Password and confirmation don't match."
                self.add_error('password', err)
                self.add_error('password_confirmation', err)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserForm

#Signup page
def signup_view(request):
    #Create user on POST
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            #Create user and login
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = User.objects.create_user(username, email, password)
            login(request, user)
            messages.success(request, "Welcome " + username + "!")
            return redirect('users:profile')
        else:
            #Show errors
            return render(request, 'users/signup_page.html', {"form": form})
    
    #Load page on GET
    else:
        form = UserForm()
        return render(request, 'users/signup_page.html', {"form": form})


#Log user out
def logout_view(request):
    logout(request)
    messages.info(request, "You have been logged out.")
    return redirect('users:login')

#User profile
@login_required
def profile(request):
    u = request.user    
    initial_profile = {
        'username': u.username,
        'email': u.email,
    }

    #Update user details
    if request.method == 'POST':
        form = UserForm(request.POST, initial=initial_profile)
        if form.is_valid():
            #Get new data
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            
            #Update model
            u.username = username
            u.email = email

            #Change password if not empty
            if password != '':
                u.set_password(password)
                messages.success(request, "Saved profile and changed password!")
            else:
                messages.success(request, "Saved profile!")

            u.save()
            return redirect('users:profile')
        
        else:
            #Render profile with errors
            return render(request, 'users/profile.html', {'form': form})

    #Display user profile
    else:
        form = UserForm(initial=initial_profile)
        return render(request, 'users/profile.html', {'form': form})

#Disable account
@login_required
def disable(request):
    #Disable account
    if request.method == 'POST':
        request.user.is_active = False
        request.user.save()
        logout(request)
        messages.success(request, 'Account disabled.')
        return redirect('users:login')

    #Show confirmation
    else:
        return render(request, 'users/disable_page.html')

users/templates/users/disable_page.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
    <div class="container has-text-centered mb-4">
        <p class="title">Are you sure you want to disable your account?</p>
    </div>

    <div class="box">           
        <form method="post">
        {% csrf_token %}
            <div class="field is-grouped is-grouped-centered">
                <div class="control">
                    <a href="{% url 'users:profile' %}" class="button is-light">Cancel</a>
                </div>
                <div class="control">
                    <button class="button is-danger">Disable Account</button>
                </div>
            </div>
        </form>
    </div>

</div>

{% endblock content %}

users/templates/users/login_page.html
{% extends "base.html" %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    {% include 'notification.html' with msg='Your account does not have access to this page' type='is-danger' %}
    {% else %}
    {% include 'notification.html' with msg='You must be logged in to access this page' type='is-danger' %}
    {% endif %}
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
{% include 'notification.html' with msg=error type='is-danger' %}
{% endfor %}
{% endif %}

<div class="section">
        <div class="container has-text-centered mb-4">
            <p class="title">Log In</p>
        </div>

        <div class="box" action="{% url 'users:login' %}">
            <form method="post">
                {% csrf_token %}
                {% include 'forms/input.html' with field=form.username label='Username' %}
                {% include 'forms/input.html' with field=form.password label='Password' %}
                <div class="field is-grouped">
                    <div class="control">
                        <a href="{% url 'users:signup' %}" class="button is-light">Sign Up</a>
                    </div>
                    <div class="control">
                        <button class="button is-link">Log In</button>
                    </div>
                </div>
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="section">
        <div class="container has-text-centered mb-4">
            <p class="title">{{ user.get_username }}'s Profile</p>
        </div>

        <div class="box">
            <form method="post">
                {% csrf_token %}
                {% include 'forms/input.html' with field=form.username label='Username' %}
                {% include 'forms/input.html' with field=form.email label='Email' %}
                {% include 'forms/input.html' with field=form.password label='Password' %}
                {% include 'forms/input.html' with field=form.password_confirmation label='Confirm Password' %}
                <div class="field is-grouped">
                    <div class="control">
                        <a href="{% url 'users:disable' %}" class="button is-danger">Disable Account</a>
                    </div>
                    <div class="control">
                        <button class="button is-link">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% block content %}
    <p>signup</p>
{% endblock %}

users/templates/users/signup_page.html
{% extends "base.html" %}
{% block content %}
    <div class="section">
        <div class="container has-text-centered mb-4">
            <p class="title">Sign Up</p>
        </div>

        <div class="box">
            <form method="post">
                {% csrf_token %}
                {% include 'forms/input.html' with field=form.username label='Username' %}
                {% include 'forms/input.html' with field=form.email label='Email' %}
                {% include 'forms/input.html' with field=form.password label='Password' %}
                {% include 'forms/input.html' with field=form.password_confirmation label='Confirm Password' %}
                <div class="field is-grouped">
                    <div class="control">
                        <a href="{% url 'users:login' %}" class="button is-light">Log In</a>
                    </div>
                    <div class="control">
                        <button class="button is-link">Sign Up</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    
{% endblock %}