Feed/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from RoutePages import views as RoutePageViews



app_name= "Feed"

urlpatterns=[
    path('', views.display_feed, name='feed'),
]

Rambler/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from Feed import views as feed_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', feed_views.display_feed, name='home'),
    path('users/', include('users.urls')),
    path('routeplanner/', include('RoutePlanner.urls')),
    path('feed/', include('Feed.urls')),
    path('weather/', include('Weather.urls')),
    path('route/', include('RoutePages.urls')),
    path('chat/', include('chat.urls')),
]

RoutePlanner/urls.py
from django.urls import path
from . import views

app_name = 'RoutePlanner'
urlpatterns = [
    path('', views.routePlanner, name='route-planner'),
    path('test/', views.getRoutes, name='test'),
    path('view/', views.showRoute, name='view-route'),
]

WalkingApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Weather/urls.py
from django.urls import path, include
from . import views

app_name = 'Weather'
urlpatterns = [
    path('', views.weather, name='weather-page'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login_page.html', form_class=LoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('disable/', views.disable, name='disable'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="has-navbar-fixed-top" lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Rambler{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/bulma.css' %}">

    {# Can later add here any app-wide overrides to bulma #}

    {# App-wide js #}
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/app.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

    {# Override these to include any page-specific js and css #}
    {% block scripts %}{% endblock %}
    {% block styles %}{% endblock %}
    {% block meta %}{% endblock %}
</head>

<body>
    {% include 'navbar.html' %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/navbar.html
<nav class="navbar is-primary is-fixed-top">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home' %}">Rambler</a>
        <a class="navbar-burger">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'Feed:feed' %}" class="navbar-item">Feed</a>
            <a href="{% url 'RoutePlanner:route-planner' %}" class="navbar-item">Route Planner</a>
            <a href="{% url 'Weather:weather-page' %}" class="navbar-item">Local Weather</a>
        </div>

        <div class="navbar-end">
            {% if user.is_authenticated %}
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Logged in as: {{ user.get_username }}</a>
                <div class="navbar-dropdown">
                    <a href="{% url 'users:profile' %}" class="navbar-item">Profile</a>
                    <a href="{% url 'Feed:feed' %}?query={{ user.get_username }}&target=users&sort=new" class="navbar-item">My Routes</a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'users:logout' %}">Log Out</a>
                </div>
            </div>

            {% else %}
            <a href="{% url 'users:login' %}" class="navbar-item">Log In</a>
            <a href="{% url 'users:signup' %}" class="navbar-item">Sign Up</a>
            {% endif %}
        </div>

    </div>
</nav>

{% if messages %}
    {% for message in messages %}
        {% include 'notification_helper.html' with msg=message %}
    {% endfor %}
{% endif %}

templates/notification.html
<div class="notification {{ type }}">
    <span>
        <button class="delete is-pulled-right"></button>
        {{ msg }}
    </span>
</div>

templates/notification_helper.html
{% if msg.tags %}
    {% if msg.tags == 'debug' %}
        {% include 'notification.html' with type='is-info is-light' %}
    {% elif msg.tags == 'info' %}
        {% include 'notification.html' with type='is-info' %}
    {% elif msg.tags == 'success' %}
        {% include 'notification.html' with type='is-success' %}
    {% elif msg.tags == 'warning'%}
        {% include 'notification.html' with type='is-warning' %}
    {% elif msg.tags == 'error' %}
        {% include 'notification.html' with type='is-danger' %}
    {% endif %}

{% else %}
    {% include 'notification.html' with type='is-info' %}
{% endif %}